version: '2'
services:
  app:
    container_name: app
    image: fatherlinux/centos5-base
    volumes:
      - ./www:/var/www/html
    tty: true
    command: /bin/bash
  php:
    container_name: php
    build: ./php
    ports:
      - '8080:80'
      - '443:443'
    volumes_from:
      - app
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  redis:
    container_name: redis
    build: ./redis
